import type { Env } from "./types";
import { createHmac, timingSafeEqual } from "node:crypto";
import { errResponse, getCookie } from "./utils";

// ── Signed-Token-Helper (Warning-Bypass + generisch) ─────────────────────────

/**
 * Generates a time-limited signed token: `<timestampMs>.<hmac-hex>`.
 * Subject-separation prevents cross-replay with session CSRF tokens.
 *
 * @param subject  Unique context string, e.g. `"warning:aB3xY9"`
 * @param secret   `SESSION_SECRET` (reuse; subject provides separation)
 * @param ttlMs    Token lifetime in milliseconds (default 5 minutes)
 */
export function generateSignedToken(subject: string, secret: string, ttlMs = 5 * 60 * 1000): string {
	const ts = Date.now() + ttlMs;
	const hmac = createHmac("sha256", secret);
	hmac.update(`${subject}:${ts}`);
	return `${ts}.${hmac.digest("hex")}`;
}

/**
 * Verifies a signed token generated by `generateSignedToken`.
 * Returns `true` only if the HMAC matches AND the token has not expired.
 */
export function verifySignedToken(token: string, subject: string, secret: string): boolean {
	const dotIdx = token.indexOf(".");
	if (dotIdx < 1) return false;
	const tsStr = token.slice(0, dotIdx);
	const mac = token.slice(dotIdx + 1);
	const ts = Number(tsStr);
	if (!Number.isFinite(ts) || Date.now() > ts) return false;
	const hmac = createHmac("sha256", secret);
	hmac.update(`${subject}:${ts}`);
	const expected = hmac.digest("hex");
	if (mac.length !== expected.length) return false;
	return timingSafeEqual(Buffer.from(mac, "utf-8"), Buffer.from(expected, "utf-8"));
}

/**
 * 🔴 SICHERHEIT: CSRF-Schutz mit Double-Submit-Cookie Pattern.
 * Token ist HMAC-basiert, kein separates Token-Storage nötig.
 *
 * Vektor: POST /api/links, POST /api/links/:code/update, etc.
 * ohne CSRF-Token kann fremde Website im Browser des Nutzers Requests auslösen
 * (Cookie wird automatisch mitgesendet trotz SameSite=Lax bei Top-Level-Navigation).
 */

/**
 * Generiert CSRF-Token basierend auf Session-ID.
 * Token muss vom Client in X-CSRF-Token Header mitgesendet werden.
 */
export function generateCsrfToken(sessionId: string, secret: string): string {
	const hmac = createHmac('sha256', secret);
	hmac.update(sessionId);
	return hmac.digest('hex');
}

/**
 * Validiert CSRF-Token mit Timing-safe Comparison.
 * Erwartet Token im X-CSRF-Token Header.
 */
export function validateCsrfToken(
	request: Request,
	sessionId: string,
	secret: string
): boolean {
	const headerToken = request.headers.get('X-CSRF-Token');
	if (!headerToken) return false;

	const expectedToken = generateCsrfToken(sessionId, secret);

	// Timing-safe comparison: verhindert Timing Attacks
	if (headerToken.length !== expectedToken.length) return false;

	const a = Buffer.from(headerToken, 'utf-8');
	const b = Buffer.from(expectedToken, 'utf-8');
	return timingSafeEqual(a, b);
}

/**
 * Gibt alle akzeptierten Origins zurück: APP_BASE_URL + den eigenen Request-Origin.
 * Damit funktioniert CSRF-Prüfung in jedem Environment (lokal, staging, prod)
 * ohne zusätzliche Konfiguration.
 */
function getAllowedOrigins(request: Request, appBaseUrl: string): string[] {
	const origins = new Set<string>([appBaseUrl]);
	try {
		const url = new URL(request.url);
		origins.add(`${url.protocol}//${url.host}`);
	} catch { /* ignore malformed URLs */ }
	return [...origins];
}

/**
 * LEGACY: Origin + X-Requested-With Check für Backwards-Compatibility.
 * Neue CSRF-Validierung läuft in Session-basierten Endpoints ab.
 */
export function validateCsrf(request: Request, env: Env): boolean {
	if (request.method !== "POST") return true;

	const origin = request.headers.get("Origin");
	if (origin === null) {
		// Kein Origin Header → non-browser caller (curl, tests, mobile app). Allow.
		return true;
	}

	// Origin present but doesn't match any allowed origin → block
	if (!getAllowedOrigins(request, env.APP_BASE_URL).includes(origin)) return false;

	// Origin matches: either a custom fetch header (X-Requested-With) or a valid
	// CSRF token header must be present. The token VALUE is validated per-handler
	// by validateMutationCsrf; here we only require the header to be present so
	// that simple form-submissions (which cannot set custom headers) remain blocked.
	return !!request.headers.get("X-Requested-With") || !!request.headers.get("X-CSRF-Token");
}

/**
 * Kombinierte CSRF-Prüfung für authentifizierte Mutation-Endpoints.
 * Gibt null zurück wenn OK, oder eine errResponse(403) bei Verstoß.
 *
 * Logik:
 * - Kein Origin Header → Non-Browser (curl, mobile) → erlaubt
 * - Foreign Origin → immer blockiert
 * - Same-Origin → erlaubt wenn X-CSRF-Token ODER X-Requested-With vorhanden
 */
export function validateMutationCsrf(
	request: Request,
	env: { APP_BASE_URL: string; SESSION_SECRET: string }
): Response | null {
	const origin = request.headers.get("Origin");
	if (!origin) return null; // Non-browser client

	if (!getAllowedOrigins(request, env.APP_BASE_URL).includes(origin)) {
		return errResponse("Invalid CSRF token", 403);
	}

	// Same-origin: Token ODER Legacy-Header erforderlich
	const hasXRequestedWith = !!request.headers.get("X-Requested-With");
	const sid = getCookie(request, "__Host-sid");
	const hasValidToken = sid
		? validateCsrfToken(request, sid, env.SESSION_SECRET)
		: false;

	if (!hasValidToken && !hasXRequestedWith) {
		return errResponse("Invalid CSRF token", 403);
	}

	return null;
}

